#!/bin/bash

#-Please specify parallel or nonparallel
#-e.g. for preprocessing and individualstats, set to 1 (parallel)
#-for groupstats, set to 0 (nonparallel)


project_dir=$1
subjectlist=$2
runlist=$3
task_folder=$4
pipeline_used=$5

config_dir='/oak/stanford/groups/menon/projects/daelsaid/2019_met/scripts/config_scripts/';

echo "paralist.parallel = '1';" >> ${config_dir}/individual_stats_bashconfig.m

# fMRI parameters
#-spm batch templates location
echo "paralist.batchtemplatepath = '/oak/stanford/groups/menon/scsnlscripts/brainImaging/mri/fmri/preprocessing/spm12/preprocessfmrimodules/batchtemplates/';" >> ${config_dir}/individual_stats_bashconfig.m

#-SPM version
echo "paralist.spmversion = 'spm12';" >> ${config_dir}/individual_stats_bashconfig.m


#-Subject list
echo "paralist.subjectlist = '${subjectlist}';" >> ${config_dir}/individual_stats_bashconfig.m

#-Run list
echo "paralist.runlist = '${runlist}';" >> ${config_dir}/individual_stats_bashconfig.m

# Please specify the data type of preprocessed images
# 'nii' for Nifti 4-D format, 'img' for Analyze 7.5 format
# If you would like the script to decide which type to use, uncomment the
# second line and comment the first line

echo "paralist.data_type = 'nii';" >> ${config_dir}/individual_stats_bashconfig.m

# Please indicate whether to use head movements (1:Yes; 0:No)
echo "paralist.include_mvmnt = 1;" >> ${config_dir}/individual_stats_bashconfig.m

#-Please specify the standard preprocessing pipeline you have used
echo "paralist.pipeline = '${swar}';" >> ${config_dir}/individual_stats_bashconfig.m


# -------------------------------------------------------------------------
# I/O parameters
# - Project directory - output of the individualstats will be saved in the
# results/taskfmri folder of the project directory

echo "paralist.projectdir = '${project_dir}';" >> ${config_dir}/individual_stats_bashconfig.m

# Please specify the foler for preprocessed data via standard pipeline
echo "paralist.preprocessed_folder= '${pipeline_used}_spm12';" >> ${config_dir}/individual_stats_bashconfig.m

# Please specify the folder holding statistics results (below 'stats_spm'
# which is generated by default)
# If you include_volrepair = 1 below, set stats_folder = 'temp_stats';

echo "paralist.stats_folder = '${task_folder}_${pipeline_used}';" >> ${config_dir}/individual_stats_bashconfig.m

# paralist.stats_folder = 'temp_stats';


# task and contrast parameters
#-Please specify the task design file (*.m)
#-If task design *.mat file already exists, please specify as a mat file (e.g., task_design.mat)
echo "paralist.task_dsgn  = 'task_design.mat';" >> ${config_dir}/individual_stats_bashconfig.m


#-Please specify the file holding contrasts
echo "paralist.contrastmat= 'contrasts.mat';" >> ${config_dir}/individual_stats_bashconfig.m
# paralist.contrastmat = [''];

#-Please specify the TR otherwise the default is 2.0 s

echo "paralist.TR = 0.49;" >> ${config_dir}/individual_stats_bashconfig.m

#-Please specify the type of serial correlations
#-other options are 'none', 'FAST'
echo "paralist.cvi = 'FAST';" >> ${config_dir}/individual_stats_bashconfig.m

#-please specify the whole brain mask
# echo "paralist.whole_brain_mask =[''];" >> ${config_dir}/individual_stats_bashconfig.m


# Please indicate whether it is based on VolRepair pipeline
# 1: use volrepair pipeline data for individual stats
# 0: use standard pipeline data
# If you set volrepair = 1, set up VolRepair section below
# If you set volrepair = 0, do not set up VolRepair section below
echo "paralist.include_volrepair = 0;" >> ${config_dir}/individual_stats_bashconfig.m

# -------------------------------------------------------------------------
# VolRepair Preprocessing Setup
# -------------------------------------------------------------------------

# Please specify the volrepair preprocessing pipeline
echo "paralist.volpipeline = '${pipeline_used}';" >> ${config_dir}/individual_stats_bashconfig.m

# Please specify the volrepair preprocessed folder
echo "paralist.volrepaired_folder = 'volrepair_spm12';" >> ${config_dir}/individual_stats_bashconfig.m

# Please specify the folder for VolRepaired data (swavrI*)
# the stats folder is under 'stats_spm8' folder (generated by default)
echo "paralist.repaired_stats   = 'stats_spm12_VolRepair';" >> ${config_dir}/individual_stats_bashconfig.m

chmod 775 ${config_dir}/individual_stats_bashconfig.m;
